services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    develop:
      watch:
        - action: sync+restart
          path: ./apps/api/src
          target: /app/apps/api/src
          initial_sync: true
        - action: rebuild
          path: package.json
        - action: rebuild
          path: apps/api/package.json
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql://shurl:shurl@database:3306/shurl
      - REDIS_URL=redis://redis:6379
    env_file:
      - apps/api/.env
    ports:
      - 3000:3000

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s

  database:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shurl
      - MYSQL_USER=shurl
      - MYSQL_PASSWORD=shurl
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  db:
