FROM oven/bun:1.3.14 AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY apps apps
RUN bun install --frozen-lockfile

USER bun
EXPOSE 3000
ENTRYPOINT [ "bun", "run", "--filter", "*/api", "dev" ]
