FROM oven/bun AS base

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/api/package.json apps/api/package.json
RUN bun install --frozen-lockfile
COPY apps/api/src apps/api/src

USER bun
WORKDIR /app/apps/api
EXPOSE 3000
ENTRYPOINT [ "bun", "dev" ]
